/**
 * Resource Validation Utilities
 * Validates external resources generated by AI to ensure quality
 */

// Trusted domains for external resources
const TRUSTED_DOMAINS = [
  "developer.mozilla.org",
  "mdn.mozilla.org",
  "react.dev",
  "reactjs.org",
  "nodejs.org",
  "javascript.info",
  "web.dev",
  "css-tricks.com",
  "github.com",
  "stackoverflow.com",
  "freecodecamp.org",
  "theodinproject.com",
  "vuejs.org",
  "angular.io",
  "docs.python.org",
  "docs.oracle.com",
  "microsoft.com/docs",
  "w3schools.com",
  "smashingmagazine.com",
  "alistapart.com",
];

/**
 * Check if a URL is from a trusted domain
 */
export const isTrustedDomain = (url) => {
  try {
    const urlObj = new URL(url);
    const hostname = urlObj.hostname.toLowerCase();

    return TRUSTED_DOMAINS.some(
      (domain) => hostname === domain || hostname.endsWith(`.${domain}`),
    );
  } catch {
    // console.warn("Invalid URL:", url);
    return false;
  }
};

/**
 * Validate external resources array
 */
export const validateExternalResources = (resources) => {
  if (!Array.isArray(resources)) {
    return { valid: false, issues: ["Not an array"] };
  }

  if (resources.length === 0) {
    return { valid: false, issues: ["Empty array"] };
  }

  const issues = [];
  const validResources = [];

  resources.forEach((resource, index) => {
    // Check required fields
    if (!resource.url) {
      issues.push(`Resource ${index + 1}: Missing URL`);
      return;
    }

    if (!resource.title) {
      issues.push(`Resource ${index + 1}: Missing title`);
      return;
    }

    // Validate URL format
    try {
      new URL(resource.url);
    } catch {
      issues.push(`Resource ${index + 1}: Invalid URL format`);
      return;
    }

    // Check if trusted domain
    if (!isTrustedDomain(resource.url)) {
      // Don't reject, just warn
    }

    // Check for video resources (not allowed)
    if (
      resource.type === "video" ||
      resource.url.includes("youtube.com") ||
      resource.url.includes("vimeo.com")
    ) {
      issues.push(
        `Resource ${index + 1}: Video resources not allowed (text-based platform)`,
      );
      return;
    }

    validResources.push(resource);
  });

  if (validResources.length < 3) {
    issues.push(
      `Only ${validResources.length} valid resources (recommended: 3-5)`,
    );
  }

  return {
    valid: validResources.length >= 2, // At least 2 valid resources
    validCount: validResources.length,
    totalCount: resources.length,
    issues,
    validResources,
  };
};

/**
 * Log validation results for debugging
 */
export const logResourceValidation = (lessonTitle, resources) => {
  const validation = validateExternalResources(resources);
  return validation;
};
